// Code generated by MockGen. DO NOT EDIT.
// Source: service/user/api/internal/repository/todo.go
//
// Generated by this command:
//
//	mockgen -source=service/user/api/internal/repository/todo.go -destination=service/user/api/internal/mocks/mock_todo_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/wokoworks/go-server/common/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoRepositoryInterface is a mock of TodoRepositoryInterface interface.
type MockTodoRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTodoRepositoryInterfaceMockRecorder
}

// MockTodoRepositoryInterfaceMockRecorder is the mock recorder for MockTodoRepositoryInterface.
type MockTodoRepositoryInterfaceMockRecorder struct {
	mock *MockTodoRepositoryInterface
}

// NewMockTodoRepositoryInterface creates a new mock instance.
func NewMockTodoRepositoryInterface(ctrl *gomock.Controller) *MockTodoRepositoryInterface {
	mock := &MockTodoRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTodoRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoRepositoryInterface) EXPECT() *MockTodoRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoRepositoryInterface) Create(ctx context.Context, todo *model.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Create(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Create), ctx, todo)
}

// Delete mocks base method.
func (m *MockTodoRepositoryInterface) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Delete), ctx, id)
}

// FindByIDAndUserID mocks base method.
func (m *MockTodoRepositoryInterface) FindByIDAndUserID(ctx context.Context, id, userID uint) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDAndUserID", ctx, id, userID)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDAndUserID indicates an expected call of FindByIDAndUserID.
func (mr *MockTodoRepositoryInterfaceMockRecorder) FindByIDAndUserID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDAndUserID", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).FindByIDAndUserID), ctx, id, userID)
}

// FindByUserID mocks base method.
func (m *MockTodoRepositoryInterface) FindByUserID(ctx context.Context, userID uint) ([]model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockTodoRepositoryInterfaceMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).FindByUserID), ctx, userID)
}

// FindByUserIDWithPage mocks base method.
func (m *MockTodoRepositoryInterface) FindByUserIDWithPage(ctx context.Context, userID uint, offset, limit int) ([]model.Todo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDWithPage", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]model.Todo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserIDWithPage indicates an expected call of FindByUserIDWithPage.
func (mr *MockTodoRepositoryInterfaceMockRecorder) FindByUserIDWithPage(ctx, userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDWithPage", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).FindByUserIDWithPage), ctx, userID, offset, limit)
}

// Update mocks base method.
func (m *MockTodoRepositoryInterface) Update(ctx context.Context, todo *model.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Update(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Update), ctx, todo)
}
