// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package server

import (
	"context"

	"github.com/fx0x55/micro-go-lab/service/inventory/rpc/internal/logic"
	"github.com/fx0x55/micro-go-lab/service/inventory/rpc/internal/svc"
	"github.com/fx0x55/micro-go-lab/service/inventory/rpc/pb"
)

type InventoryServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInventoryServiceServer
}

func NewInventoryServiceServer(svcCtx *svc.ServiceContext) *InventoryServiceServer {
	return &InventoryServiceServer{
		svcCtx: svcCtx,
	}
}

// GetStock 查询指定 SKU 的库存可用量（只读）
func (s *InventoryServiceServer) GetStock(ctx context.Context, in *pb.GetStockRequest) (*pb.GetStockResponse, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}
