// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/fx0x55/micro-go-lab/service/user/rpc/internal/logic"
	"github.com/fx0x55/micro-go-lab/service/user/rpc/internal/svc"
	"github.com/fx0x55/micro-go-lab/service/user/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// ValidateUser 验证用户是否存在
func (s *UserServiceServer) ValidateUser(ctx context.Context, in *pb.ValidateUserRequest) (*pb.ValidateUserResponse, error) {
	l := logic.NewValidateUserLogic(ctx, s.svcCtx)
	return l.ValidateUser(in)
}

// GetUser 获取用户信息
func (s *UserServiceServer) GetUser(ctx context.Context, in *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
