server:
  port: 8081
  read_timeout: 10s
  write_timeout: 10s

database:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  dbname: orders_db
  max_open_conns: 25
  max_idle_conns: 10

user_svc:
  grpc_addr: "localhost:9090"

jwt:
  secret: change-me-in-production
  expiration: 24h

telemetry:
  enabled: true
  endpoint: "localhost:4317"
