// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package inventoryservice

import (
	"context"

	"github.com/fx0x55/micro-go-lab/service/inventory/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetStockRequest  = pb.GetStockRequest
	GetStockResponse = pb.GetStockResponse

	InventoryService interface {
		// GetStock 查询指定 SKU 的库存可用量（只读）
		GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	}

	defaultInventoryService struct {
		cli zrpc.Client
	}
)

func NewInventoryService(cli zrpc.Client) InventoryService {
	return &defaultInventoryService{
		cli: cli,
	}
}

// GetStock 查询指定 SKU 的库存可用量（只读）
func (m *defaultInventoryService) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	client := pb.NewInventoryServiceClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}
