// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	"github.com/fx0x55/micro-go-lab/service/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserRequest       = pb.GetUserRequest
	GetUserResponse      = pb.GetUserResponse
	ValidateUserRequest  = pb.ValidateUserRequest
	ValidateUserResponse = pb.ValidateUserResponse

	CreateUserRequest       = pb.CreateUserRequest
	CreateUserResponse      = pb.CreateUserResponse
	AuthenticateRequest     = pb.AuthenticateRequest
	AuthenticateResponse    = pb.AuthenticateResponse

	UserService interface {
		// ValidateUser 验证用户是否存在
		ValidateUser(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserResponse, error)
		// GetUser 获取用户信息
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		// CreateUser 创建用户
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
		// Authenticate 校验用户名+密码
		Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// ValidateUser 验证用户是否存在
func (m *defaultUserService) ValidateUser(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ValidateUser(ctx, in, opts...)
}

// GetUser 获取用户信息
func (m *defaultUserService) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// CreateUser 创建用户
func (m *defaultUserService) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

// Authenticate 校验用户名+密码
func (m *defaultUserService) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.Authenticate(ctx, in, opts...)
}
